import test from 'node:test';
import assert from 'node:assert/strict';
import {rentCountdown} from '../assets/rent-countdown.mjs';
const tenant={id:2,apartment_id:1,is_active:true};
const now=new Date('2026-09-30T23:59:59Z');
const charge=(extra={})=>({id:1,tenant_id:2,amount_minor:100,paid_amount_minor:100,due_date:'2026-09-05',...extra});
test('inactive until first full payment',()=>assert.equal(rentCountdown([charge({paid_amount_minor:50})],tenant,now).days,null));
test('first full payment activates next agreed monthly date',()=>assert.deepEqual(rentCountdown([charge()],tenant,now),{label:'5 days until rent is due',due:'2026-10-05',days:5,projected:true}));
test('payment timestamp never shifts agreed date',()=>assert.equal(rentCountdown([charge({paid_at:'2026-09-29'})],tenant,now).due,'2026-10-05'));
test('recorded charge overrides estimate',()=>assert.equal(rentCountdown([charge(),charge({id:2,paid_amount_minor:0,due_date:'2026-10-10'})],tenant,now).due,'2026-10-10'));
test('oldest unpaid charge wins even with later paid charges',()=>assert.equal(rentCountdown([charge(),charge({id:2,paid_amount_minor:50,due_date:'2026-09-01'})],tenant,now).label,'29 days overdue'));
test('due today at UTC boundary',()=>assert.equal(rentCountdown([charge(),charge({id:2,paid_amount_minor:0,due_date:'2026-09-30'})],tenant,now).label,'Due today'));
test('February clamp handles leap year',()=>assert.equal(rentCountdown([charge({due_date:'2028-01-31'})],tenant,now).due,'2028-02-29'));
test('year rollover',()=>assert.equal(rentCountdown([charge({due_date:'2026-12-31'})],tenant,now).due,'2027-01-31'));
test('no new estimated charges for unassigned resident',()=>assert.equal(rentCountdown([charge()],{...tenant,apartment_id:null},now).due,null));
test('other tenants payments cannot activate countdown',()=>assert.equal(rentCountdown([charge({tenant_id:3})],tenant,now).days,null));
test('correcting payment to partial removes full-payment activation',()=>assert.equal(rentCountdown([charge({paid_amount_minor:99})],tenant,now).days,null));
test('next paid period advances reminder',()=>assert.equal(rentCountdown([charge(),charge({id:2,due_date:'2026-10-05'})],tenant,now).due,'2026-11-05'));
test('estimated missed date stays overdue instead of rolling forward',()=>assert.equal(rentCountdown([charge({due_date:'2026-07-05'})],tenant,now).due,'2026-08-05'));
